language: node_js
node_js: '4.0'
compiler: clang-3.6
env:
  global:
  - CXX: clang-3.6
  - GH_DEPLOYER: RussTheAerialist
  - GH_REPO: github.com/nodebotssea/website.git
  - secure: Ij7D2GNBs0TC/GBq9ebpXaaUEMpdQIpmTfiq1SfLJah2whUoFcOFx9SAfKk5QI987f/mCH0mBWnQ79w4L+mxr2jUvseY2XsLRHyA7fVowc2fam+qle/IUwsqlPOvdor7cqzODoXuBvBGzEZaHuEE3iTALk6zLedmvZytXlqALUAATUiZ/Wm4AjRQHyaOd3ynBzFcGkZ2YL0O0p4H67OJBcW00tFxbHDOAephEJFjmNofb12LugHU7GuQOzUt66OCLNHAfycmUPVbvTHHOx2en43FVZlNqzqErkP6hnE61QC12jLbF+aEpfokH0maYO1BsxLCjXfb53hBUzcqnj1kNV82ga6haq02sacLGEXJDO0cqRqIaqPtIOj8Yi32MfnivoZdEZ97vkrnkY7GjLLbRU8XD6HI8Gta49Atx0QsQllYqemZ1LGXJWW6+wJLLt8kzs+2qKXR7uublHFnHc73MM6NleLtp0dlrRB8+za7AvlAcPBRjETLcWUcWd6K6KaCUmPdLRba8TiXuGmdDSd9SdTvfEQ7D/NOZDWqlw5h5rOOUyMpHQ0Tv4wIXHTk9/coiizCRpdAh8pe0d6OWvYWw2xex9KSE+b6w/rKf61Y/7X9OqHvF6IY8CcbVQVp9oROmp7z0aiA/VG/76TOUtVh9NwXJfP8KQngbYAenO0P4vw=
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - g++-4.8
before_install:
- gem install sass
after_success:
- "./.travis/deploy.sh"
